### ISSUE TITLE
user role align error

### ISSUE THREAD

**Issue by yx135790** [bitnami/bitnami-docker-testlink#121] opened 2021-11-10 02:37 UTC
Hi 

I recently migrate from VM to Kubernetes and we are using Bitnami testlink image
so far everything else looks good but when  I  tried to align roles . there is just a blank area which suppose to be my user list

also in the logo 

```
[Tue Nov 09 11:37:03.212530 2021] [php7:error] [pid 171] [client 10.42.10.0:7418] PHP Fatal error: Uncaught Error: Object of class stdClass could not be converted to string in /opt/bitnami/testlink/gui/templates_c/eea1408e299ce693619c19399852a6bca9e3b389_0.file.usersAssign.tpl.php:119
Stack trace:
#0 /opt/bitnami/testlink/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_618a5bd267fad5_50084949()
#1 /opt/bitnami/testlink/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode()
#2 /opt/bitnami/testlink/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render()
#3 /opt/bitnami/testlink/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(232): Smarty_Internal_Template->render()
#4 /opt/bitnami/testlink/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(134): Smarty_Internal_TemplateBase->_execute()
#5 /opt/bitnami/testlink/lib/usermanagement/usersAssign.php(136): Smarty_Internal_TemplateBase->display()
#6 {main}\n thrown in /opt/bitnami/testlink/gui/templates_c/eea1408e299ce693619c19399852a6bca9e3b389_0.file.usersAssign.tpl.php on line 119, referer: http://10.228.75.31:32740/lib/usermanagement/usersAssign.php?featureType=testproject
```

**Comment by alvneiayu** [comment] 2021-11-10 12:44
hi @yx135790 

First of all, thanks a lot for using our products. Could you share with me the Testlink version that you are using? It seems that this is a Testlink problem. It is not a problem with the container or the configuration. Take a look this case:

https://forum.testlink.org/viewtopic.php?t=8222

So, please share with me the Testlink version and I would invite you to open a ticket in the Testlink forum. I think that they will help you with this specific problem.

Thanks a lot

Álvaro

**Comment by yx135790** [comment] 2021-11-11 02:41
Hi @alvneiayu

Thanks for your help. The Testlink version is 1.9.20 ,which is updated from 1.9.13 (on VM)

Basically this is how I do it 
1. Start a new testlink in docker or K8s (I have tried both).
2. Remove the bitnami_testlink database in Mariadb and create a new empty on with the same name.
3. Dump testlinkdb (1.9.13) and recover it to bitnami_testlink(1.9.20)
4. Run the DB upgrade script that i download from testlink repo [teslink-code github ](https://github.com/testlinkopensourcetrms/testlink-code
```
1.9.13 => 1.9.14 =>
1.9.15 => 1.9.16 => 1.9.17 => 1.9.18 => 1.9.19 => 1.9.20
```
5. The DB upgraded with no errors 
6. login in to the web ui and the error emerge  as below
<img width="1116" alt="Screen Shot 2021-11-11 at 10 25 48 AM" src="https://user-images.githubusercontent.com/18626087/141227720-f104b501-439c-493f-9fb1-f469bbab2b9b.png">
 

also in the logo

```
[Tue Nov 09 11:37:03.212530 2021] [php7:error] [pid 171] [client 10.42.10.0:7418] PHP Fatal error: Uncaught Error: Object of class stdClass could not be converted to string in /opt/bitnami/testlink/gui/templates_c/eea1408e299ce693619c19399852a6bca9e3b389_0.file.usersAssign.tpl.php:119
Stack trace:
#0 /opt/bitnami/testlink/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_618a5bd267fad5_50084949()
#1 /opt/bitnami/testlink/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode()
#2 /opt/bitnami/testlink/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render()
#3 /opt/bitnami/testlink/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(232): Smarty_Internal_Template->render()
#4 /opt/bitnami/testlink/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(134): Smarty_Internal_TemplateBase->_execute()
#5 /opt/bitnami/testlink/lib/usermanagement/usersAssign.php(136): Smarty_Internal_TemplateBase->display()
#6 {main}\n thrown in /opt/bitnami/testlink/gui/templates_c/eea1408e299ce693619c19399852a6bca9e3b389_0.file.usersAssign.tpl.php on line 119, referer: http://10.228.75.31:32740/lib/usermanagement/usersAssign.php?featureType=testproject

```

**Comment by yx135790** [comment] 2021-11-11 03:05
New information :

I did the whole process again ,but this time I only up graded to 1.9.19 using `bitnami/testlink:1.9.19`
Looks good so far , The use assign role showed up with no error in the log

**Comment by yx135790** [comment] 2021-11-11 03:15
The same thing happened when I upgrade it from 1.9.19 to 1.9.20

**Comment by yx135790** [comment] 2021-11-11 03:39
New information 

When I use image `bitnami/testlink:1.9.20-ol-7-r29` it works just fine
But seems like this `ol` series has been deprecated.
May I Know what does `ol` stands for ? and what is the difference between these two series (`ol`  and `Debian`)

**Comment by yx135790** [comment] 2021-11-12 07:29
`bitnami/testlink:1.9.20-debian-10-r450` works fine
`bitnami/testlink:1.9.20-debian-10-r522` user role assign error

**Comment by alvneiayu** [comment] 2021-11-15 09:22
hi @yx135790 

It seems that we have included some changes in our scripts. Could you test with the version 1.9.20-debian-10-r500 release to verify that the error persists, please?

Thanks a lot

Álvaro

**Comment by yx135790** [comment] 2021-11-15 09:41
Hi Álvaro @alvneiayu :

Thanks for the feedback
Yes, just tried `bitnami/testlink:1.9.20-debian-10-r500`  and the problem persists 

Leo

**Comment by alvneiayu** [comment] 2021-11-18 12:25
hi @yx135790 

I checked and the changes that we have included are not critical changes to generate this issue (Update Apache, PHP, etc). I am trying to reproduce the problem but I can not. I know that it is a little bit tedious but could you help me to reduce the range of versions, please? I mean, you have checked with the `bitnami/testlink:1.9.20-debian-10-r500` so could you check with other versions between r500 to r470? Just to understand when it is broken for you and to try to find some information about it.

Thanks a lot for your help

Álvaro

**Comment by yx135790** [comment] 2021-11-19 09:41
@alvneiayu 
Hi 
I just narrowed the scope to `bitnami/testlink:1.9.20-debian-10-r497` to `bitnami/testlink:1.9.20-debian-10-r498`
So 497 has not error ,but 498 has the error as mentioned

**Comment by alvneiayu** [comment] 2021-11-22 15:26
hi @yx135790 

in the 498 release, the container is using the last PHP version released. We are not including our scripts changes. It was just a PHP upgrade. So it is related with testlink and this php version (7.4.23-0).

**Comment by yx135790** [comment] 2021-11-24 07:54
hi @alvneiayu 

Thanks, really appreciate your help on this. Do you think maybe my testlink database has something slightly different ?

**Comment by yx135790** [comment] 2021-11-24 08:06
> 

I'm not say it has something unique, I haven't had a chance to compare.

**Comment by rafariossaa** [comment] 2021-11-24 09:23
Hi,
  Does this happen when using a clean (without older data migrated) testlink deployment ?
  Maybe this happens because the data migrated.

**Comment by yx135790** [comment] 2021-11-25 02:00
@rafariossaa  
No , only when I migrate.
I guess this is not a big issue as I found the cause , which is the PHP version. 
Thanks for the help. you may close this issue

**Comment by rafariossaa** [comment] 2021-11-25 15:41
You are welcome.
I am closing this issue.

**Closed by rafariossaa** 2021-11-25 15:41 UTC

**Comment by turbolocust** [comment] 2022-03-18 08:19
I can confirm that this issue still exists (r671). It is not related to migrating data in our case. Currently, we stick with r497. I also highly disagree that this is not supposed to be a big issue, since it practically makes the software unusable to a certain degree, i.e. it is broken.

I would very much like to see a proper solution to this. Sticking with an older version is silly security-wise and having to maintain an image on our own which provides a solution to this, somehow makes this image obsolete in my opinion.

**Comment by rafariossaa** [comment] 2022-03-18 08:40
Please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-testlink#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.
If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
