### ISSUE TITLE
Container fail immediately after start

### ISSUE THREAD

**Issue by Rohlik** [bitnami/bitnami-docker-testlink#56] opened 2017-11-24 13:45 UTC
**Description**

Container immediately fail after start with error.

**Steps to reproduce the issue:**
```
docker run -p 8080:80  -v /opt/testlink:/bitnami bitnami/testlink
```
**Describe the results you received:**
```
Welcome to the Bitnami testlink container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-testlink
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-testlink/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing apache
apache  INFO  ==> Patching httpoxy...
Error executing 'postInstallation': EEXIST: file already exists, symlink '/bitnami/apache/conf' -> '/opt/bitnami/apache/conf'
```
**Describe the results you expected:**

Running container

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

- Output of `docker info`:

```
Containers: 7
 Running: 0
 Paused: 0
 Stopped: 7
Images: 21
Server Version: 17.05.0-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.2.2.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.4 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.796GiB
Name: devel-tro.domain.cz
ID: RXMM:KH5W:CN3R:YFFZ:B7M4:U2QF:PLSW:MSLI:O4MJ:CUTB:LLR6:JAUV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: overlay: the backing xfs filesystem is formatted without d_type support, which leads to incorrect behavior.
         Reformat the filesystem with ftype=1 to enable d_type support.
         Running without d_type support will not be supported in future releases.```

**Comment by carrodher** [comment] 2017-11-27 10:30
It seems that your local directory `/opt/bitnami/` already contains a folder `/apache/conf`. Can you remove it and try again? For that, you can execute the following command
```
rm -rf /opt/testlink/apache/conf
```

If you use a new folder instead of `/opt/testlink/`, the issue persist?

If this solution doesn't work, you can try removing the container and the attached volumes:
```
docker stop YOUR_CONTAINER_ID
docker rm YOUR_CONTAINER_ID
docker volume rm YOUR_VOLUME_ID
```

**Comment by Rohlik** [comment] 2017-11-28 12:43
I removed all files in `conf` dir and then I got this error:
```
Welcome to the Bitnami testlink container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-testlink
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-testlink/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing apache
Error executing 'postInstallation': Module mod_version is not present in the configuration file, you need to provide a module identifier in the options parameter along with the module name
```

Also using new folder with new container give me the same error.

**Comment by gferreyra91** [comment] 2017-11-30 14:33
Can be something related with selinux?

**Comment by Rohlik** [comment] 2017-11-30 16:08
We have selinux in _disable_ mode.

**Comment by juan131** [comment] 2017-12-01 10:37
Hi @Rohlik 

What do you exactly have on your local directory `/opt/testlink/apache/`? Could you run the command below and share the output?

```
tree /opt/testlink/apache/
```

> Please note you might need to install tree on your System by running: yum install tree -y

**Comment by Rohlik** [comment] 2017-12-04 08:07
`tree` before container start:
```
# tree /opt/test/
/opt/test/
```
and now `tree` after command `docker run -p 8080:80 -ti -v /opt/test:/bitnami bitnami/testlink`:
```
# tree /opt/test/
/opt/test/
└── apache
    └── conf
        ├── bitnami
        │   ├── bitnami.conf
        │   └── certs
        │       ├── server.crt
        │       └── server.key
        ├── deflate.conf
        ├── extra
        │   ├── httpd-autoindex.conf
        │   ├── httpd-dav.conf
        │   ├── httpd-default.conf
        │   ├── httpd-info.conf
        │   ├── httpd-languages.conf
        │   ├── httpd-manual.conf
        │   ├── httpd-mpm.conf
        │   ├── httpd-multilang-errordoc.conf
        │   ├── httpd-ssl.conf
        │   ├── httpd-userdir.conf
        │   ├── httpd-vhosts.conf
        │   └── proxy-html.conf
        ├── httpd.conf
        ├── magic
        ├── mime.types
        ├── original
        │   ├── extra
        │   │   ├── httpd-autoindex.conf
        │   │   ├── httpd-dav.conf
        │   │   ├── httpd-default.conf
        │   │   ├── httpd-info.conf
        │   │   ├── httpd-languages.conf
        │   │   ├── httpd-manual.conf
        │   │   ├── httpd-mpm.conf
        │   │   ├── httpd-multilang-errordoc.conf
        │   │   ├── httpd-ssl.conf
        │   │   ├── httpd-userdir.conf
        │   │   ├── httpd-vhosts.conf
        │   │   └── proxy-html.conf
        │   └── httpd.conf
        └── vhosts
            └── htaccess

9 directories, 32 files
```

**Comment by juan131** [comment] 2017-12-04 12:41
I'm still unable to reproduce it. Your error complains about a missing module (mod_version) but once I run `docker-compose up` I didn't find any issue and the module is available:

```
$ docker exec -it bitnamidockertestlink_testlink_1 ls -la /opt/bitnami/apache/modules | grep mod_version
$ docker exec -it bitnamidockertestlink_testlink_1 cat /opt/bitnami/apache/conf/httpd.conf | grep mod_version
LoadModule version_module modules/mod_version.so
$ docker exec -it bitnamidockertestlink_testlink_1 /opt/bitnami/apache/bin/apachectl -M | grep version_module
version_module (shared)
```

**Comment by Rohlik** [comment] 2017-12-04 13:44
I ran container twice, first I got error with `symlink` problem and second time I got error with missing `mod_version`:
```
[root@devel-tro ~]# docker logs f3a319483e23

Welcome to the Bitnami testlink container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-testlink
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-testlink/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing apache
apache  INFO  ==> Patching httpoxy...
Error executing 'postInstallation': EEXIST: file already exists, symlink '/bitnami/apache/conf' -> '/opt/bitnami/apache/conf'

Welcome to the Bitnami testlink container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-testlink
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-testlink/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing apache
Error executing 'postInstallation': Module mod_version is not present in the configuration file, you need to provide a module identifier in the options parameter along with the module name
```
I also tried cat the `httpd.conf` file:
```
[root@devel-tro ~]# docker start f3a319483e23; docker exec -ti f3a319483e23 cat /opt/bitnami/apache/conf/httpd.conf
f3a319483e23
cat: /opt/bitnami/apache/conf/httpd.conf: No such file or directory
```

**Comment by chipironcin** [comment] 2017-12-07 13:44
@Rohlik 
To start a Bitnami Testlink from scratch using containers you should use the docker-compose as explained in the README.md file:
```
docker-compose up -d
```

The option `-v /opt/testlink:/bitnami` is meant to mount an already initialized folder.
Let me recap:
When launching the docker-compose, one of the containers will be Testlink + Apache. It will symlink data and configuration from Apache and Testlink from `/opt/bitnami` (installdir) to `/bitnami`.
`/bitnami` is set in the default docker-compose to be mapped to a volume in Docker.

If you want to mount a folder of your host to the container so you can preserve your data, you need to follow this section of the README file: https://github.com/bitnami/bitnami-docker-testlink#persisting-your-application

What seems to have happened to you is that the folder you mounted (`/opt/testlink` or `/opt/test`) contains data about Apache from a previous run but it was a failed run so the file `.initialized` was not generated. When you try to run it again, it will try to reinitialize Apache (because it wont find the initialized file) and will error out as the folder already exists.

Solution?
Remove everything inside the folder you want to mount in the container, modify the docker-compose file to use that folder instead of a default Docker volume and bring up that docker-compose.

**Comment by Rohlik** [comment] 2017-12-11 09:54
@chipironcin Thx for your nice answer.
I tried this according your how-to:
```
curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-testlink/master/docker-compose.yml > docker-compose.yml
docker-compose up -d
docker-compose logs -f
```
And I got this logs:
```
Attaching to testlink_testlink_1, testlink_mariadb_1
testlink_1  |
testlink_1  | Welcome to the Bitnami testlink container
testlink_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-testlink
testlink_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-testlink/issues
testlink_1  | Send us your feedback at containers@bitnami.com
testlink_1  |
mariadb_1   |
mariadb_1   | Welcome to the Bitnami mariadb container
mariadb_1   | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb_1   | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb_1   | Send us your feedback at containers@bitnami.com
mariadb_1   |
mariadb_1   | WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
mariadb_1   | nami    INFO  Initializing mariadb
mariadb_1   | mariadb INFO  ==> Cleaning data dir...
mariadb_1   | mariadb INFO  ==> Configuring permissions...
mariadb_1   | mariadb INFO  ==> Validating inputs...
mariadb_1   | mariadb WARN  Allowing the "rootPassword" input to be empty
mariadb_1   | mariadb INFO  ==> Initializing database...
testlink_1  | nami    INFO  Initializing apache
testlink_1  | apache  INFO  ==> Patching httpoxy...
testlink_1  | Error executing 'postInstallation': EEXIST: file already exists, symlink '/bitnami/apache/conf' -> '/opt/bitnami/apache/conf'
testlink_testlink_1 exited with code 1
mariadb_1   | Error executing 'postInstallation': MySQL command failed to run. Error:
mariadb_1   |  ERROR 1010 (HY000) at line 1: Error dropping database (can't rmdir './test', errno: 39 "Directory not empty")
mariadb_1   |
testlink_mariadb_1 exited with code 1
```

Sadly, I have same problem as before even with docker-compose.

**Comment by chipironcin** [comment] 2017-12-12 15:22
Hey @Rohlik 
I think I found the root of your issues.

Using Overlay storage driver in CentOS or RHEL produce the same symptoms.

Could you please check this other issue and confirm?
https://github.com/bitnami/bitnami-docker-testlink/issues/17
https://github.com/bitnami/bitnami-docker-testlink/issues/17#issuecomment-282265377

**Comment by Rohlik** [comment] 2017-12-22 14:15
I tried on `xfs` filesystem and it is working like a charm. Maybe for future generation it can be handy put some information to Readme about problem with Overlay storage driver. What you thing?

**Comment by chipironcin** [comment] 2017-12-22 15:22
Yes, we are working on it as we need to update all our README files.
Thanks for posting back. I am closing this thread now. Please open a new one if you find any other issue with Bitnami Testlink Docker container :)

**Closed by chipironcin** 2017-12-22 15:22 UTC
